Add last exit code to shell prompt

diff --git a/shell/bashrc b/shell/bashrc
--- a/shell/bashrc
+++ b/shell/bashrc
@@ -16,6 +16,7 @@
   . /usr/share/bash-completion/bash_completion
 
 __ps1() {
+  last_exit_code="$?"
   # colors
   local x='\[\017\]'     # reset
   local n='\[\033[0m\]'  # normal
@@ -26,18 +27,19 @@ __ps1() {
 
   # check if user is root
   local U
-  [[ "$(id -u)" -eq 0 ]] && U='#' && b=$r || U='$'
+  if [[ "$(id -u)" -eq 0 ]]; then
+    U='#'
+    b=$r
+  else
+    U='$'
+  fi
 
-  # K8s info
-  local k8sinfo
-
-  # Check if k8sinfo is desired
-  if [[ -n "$PS1_K8S_INFO" ]]; then
-    context=$(kubectl config current-context 2>/dev/null)
-    namespace=$(kubens -c 2>/dev/null)
-    [[ -n "$context" ]] && k8sinfo="$k8sinfo$b""Context: $w$context "
-    [[ -n "$namespace" ]] && k8sinfo="$k8sinfo$b""Namespace: $w$namespace"
-    [[ -n "$k8sinfo" ]] && k8sinfo="$w╔ $k8sinfo $w\n╚ "
+  # check exit code
+  local R
+  if [[ $last_exit_code -eq 0 ]]; then
+    R='✅'
+  else
+    R='❌'
   fi
 
   ## Git info
@@ -89,7 +91,7 @@ __ps1() {
   fi
 
   # Final arrangement for prompt
-  PS1="$x$k8sinfo$b\u@\h $w\w $gitinfo$b$U $n"
+  PS1="$x$R $b\u@\h $w\w $gitinfo$b$U $n"
 }
 
 PROMPT_COMMAND="__ps1"
